# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmer',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='programmer',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
